name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: '${{ secrets.GCP_PROJECT }}' # TODO: update to your Google Cloud project ID
  REGION: '${{ secrets.GCP_REGION }}' # TODO: update to your region
  SERVICE: '${{ secrets.SERVICE_NAME }}' # TODO: update to your service name
  JSON_KEY: '${{ secrets.GCP_SA_KEY }}'
  WORKLOAD_ID: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout Code'
        uses: 'actions/checkout@v2'

      - name: 'Build Docker image'
        run: |
          docker build -t qr-generator-and-url-shortener .
          
      - name: 'Tag Docker image'
        run: |
          docker tag qr-generator-and-url-shortener gcr.io/${{ env.PROJECT_ID }}/qr-generator-and-url-shortener

     # Authenticate using Workload Identity
      - name: 'Authenticate with Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/${{ env.WORKLOAD_ID }}/providers/${{ env.WORKLOAD_ID }}'

      - name: 'Push Docker image'
        run: |
          docker push gcr.io/${{ env.PROJECT_ID }}/qr-generator-and-url-shortener

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image gcr.io/${{ env.PROJECT_ID }}/qr-generator-and-url-shortener \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated
